version: '3'

services:
  app:
    build: .
    command: wait-for db:3306 -t 40 -- ./start.sh
    ports:
      - 8000:3000
    volumes:
      - .:/home/node/app
    depends_on:
      - db
  
  db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./dbdata:/var/lib/mysql
# efemero === passageiro